"""Load generation.

Two engines, one result shape:

* ``k6``       — the real Grafana k6 binary, driven with a generated script and
                 parsed from its JSON summary export.
* ``builtin``  — a threaded httpx generator used when k6 is not installed.

Both return the same dict so the verdict logic never needs to care which ran.
"""

from __future__ import annotations

import json
import math
import statistics
import subprocess
import tempfile
import threading
import time
from pathlib import Path
from typing import Any, Callable

import httpx

from core.settings import K6_BIN
from core.toolchain import get as tool_get

Logger = Callable[[str], None]

K6_SCRIPT_TEMPLATE = """// Generated by ChaosGate — do not edit by hand.
import http from "k6/http";
import { check, sleep } from "k6";
import { Rate, Trend } from "k6/metrics";

const gateErrors = new Rate("gate_errors");
const gateLatency = new Trend("gate_latency", true);

const BASE = __ENV.TARGET;
const ENDPOINTS = %(endpoints)s;

export const options = {
  vus: %(vus)d,
  duration: "%(duration)s",
  thresholds: {
    http_req_failed: ["rate<%(error_rate)s"],
    http_req_duration: ["p(95)<%(p95)d"],
  },
  summaryTrendStats: ["avg", "min", "med", "p(90)", "p(95)", "p(99)", "max"],
};

export default function () {
  for (const ep of ENDPOINTS) {
    const url = `${BASE}${ep.path}`;
    const params = { headers: ep.headers || {}, tags: { path: ep.path } };
    let res;
    if (ep.method === "GET" || ep.method === "HEAD") {
      res = http.request(ep.method, url, null, params);
    } else {
      res = http.request(ep.method, url, ep.body || null, params);
    }
    const ok = res.status >= 200 && res.status < 400;
    gateErrors.add(!ok);
    gateLatency.add(res.timings.duration);
    check(res, { [`${ep.method} ${ep.path} is 2xx/3xx`]: () => ok });
  }
  sleep(%(sleep)s);
}
"""


def _histogram(values: list[float], buckets: int = 12) -> list[int]:
    if not values:
        return [0] * buckets
    lo, hi = min(values), max(values)
    if hi <= lo:
        return [len(values)] + [0] * (buckets - 1)
    width = (hi - lo) / buckets
    counts = [0] * buckets
    for value in values:
        idx = min(buckets - 1, int((value - lo) / width))
        counts[idx] += 1
    return counts


def _percentile(sorted_values: list[float], q: float) -> float:
    if not sorted_values:
        return 0.0
    idx = min(len(sorted_values) - 1, max(0, int(math.ceil(q * len(sorted_values))) - 1))
    return sorted_values[idx]


def _empty_result(engine: str, reason: str) -> dict[str, Any]:
    return {
        "engine": engine,
        "ok": False,
        "degraded": True,
        "reason": reason,
        "samples": 0,
        "errors": 0,
        "error_rate": 0.0,
        "p95_ms": 0.0,
        "avg_ms": 0.0,
        "rps": 0.0,
        "histogram": [0] * 12,
        "latencies": [],
    }


# --------------------------------------------------------------------- builtin
def run_builtin(
    base: str,
    endpoints: list[dict[str, Any]],
    vus: int,
    duration: float,
    log: Logger,
) -> dict[str, Any]:
    latencies: list[float] = []
    errors = 0
    total = 0
    status_counts: dict[str, int] = {}
    lock = threading.Lock()
    stop_at = time.time() + duration

    def worker() -> None:
        nonlocal errors, total
        with httpx.Client(timeout=6.0, follow_redirects=True) as client:
            while time.time() < stop_at:
                for ep in endpoints:
                    method = (ep.get("method") or "GET").upper()
                    path = ep.get("path") or "/"
                    url = base.rstrip("/") + path
                    t0 = time.perf_counter()
                    try:
                        res = client.request(
                            method,
                            url,
                            headers=ep.get("headers") or None,
                            content=ep.get("body") or None,
                        )
                        ms = (time.perf_counter() - t0) * 1000
                        bucket = f"{res.status_code // 100}xx"
                        failed = res.status_code >= 400
                    except Exception:
                        ms = (time.perf_counter() - t0) * 1000
                        bucket = "error"
                        failed = True
                    with lock:
                        latencies.append(ms)
                        total += 1
                        status_counts[bucket] = status_counts.get(bucket, 0) + 1
                        if failed:
                            errors += 1
                    if time.time() >= stop_at:
                        break
                time.sleep(0.01)

    workers = max(2, min(int(vus), 32))
    log(f"builtin generator: {workers} workers × {duration:.0f}s → {base}")
    threads = [threading.Thread(target=worker, daemon=True) for _ in range(workers)]
    for t in threads:
        t.start()
    for t in threads:
        t.join(timeout=duration + 10)

    if not latencies:
        return _empty_result("builtin", "no samples were collected")

    ordered = sorted(latencies)
    err_rate = errors / max(1, total)
    return {
        "engine": "builtin",
        "ok": True,
        "degraded": True,
        "reason": "k6 binary not installed — used the in-process generator",
        "samples": total,
        "errors": errors,
        "error_rate": round(err_rate, 5),
        "p95_ms": round(_percentile(ordered, 0.95), 2),
        "p99_ms": round(_percentile(ordered, 0.99), 2),
        "med_ms": round(_percentile(ordered, 0.50), 2),
        "min_ms": round(ordered[0], 2),
        "max_ms": round(ordered[-1], 2),
        "avg_ms": round(statistics.mean(ordered), 2),
        "rps": round(total / max(0.1, duration), 2),
        "vus": workers,
        "duration_s": round(duration, 1),
        "status_counts": status_counts,
        "histogram": _histogram(ordered),
        "latencies": [round(v, 3) for v in ordered[:5000]],
    }


# -------------------------------------------------------------------- real k6
def build_script(endpoints: list[dict[str, Any]], vus: int, duration: str, p95: int, error_rate: float) -> str:
    normalized = [
        {
            "method": (ep.get("method") or "GET").upper(),
            "path": ep.get("path") or "/",
            "headers": ep.get("headers") or {},
            "body": ep.get("body"),
        }
        for ep in endpoints
    ] or [{"method": "GET", "path": "/health", "headers": {}, "body": None}]
    return K6_SCRIPT_TEMPLATE % {
        "endpoints": json.dumps(normalized, indent=2),
        "vus": max(1, int(vus)),
        "duration": duration,
        "p95": int(p95),
        "error_rate": error_rate,
        "sleep": 0.1,
    }


def _metric(summary: dict[str, Any], name: str) -> dict[str, Any]:
    return ((summary.get("metrics") or {}).get(name) or {})


def _mval(summary: dict[str, Any], name: str, *keys: str, default: float = 0.0) -> float:
    metric = _metric(summary, name)
    values = metric.get("values") if isinstance(metric.get("values"), dict) else metric
    for key in keys:
        if isinstance(values, dict) and key in values and values[key] is not None:
            try:
                return float(values[key])
            except (TypeError, ValueError):
                continue
    return default


def parse_k6_summary(summary: dict[str, Any], duration: float) -> dict[str, Any]:
    """Translate a k6 --summary-export document into the ChaosGate shape."""
    count = _mval(summary, "http_reqs", "count")
    rps = _mval(summary, "http_reqs", "rate")
    failed_rate = _mval(summary, "http_req_failed", "rate", "value")
    passes = _mval(summary, "http_req_failed", "passes")
    fails = _mval(summary, "http_req_failed", "fails")
    # k6 records "passes" as the number of FAILED requests for http_req_failed.
    errors = passes if passes else round(failed_rate * count)

    p95 = _mval(summary, "http_req_duration", "p(95)", "p95")
    p99 = _mval(summary, "http_req_duration", "p(99)", "p99")
    avg = _mval(summary, "http_req_duration", "avg")
    med = _mval(summary, "http_req_duration", "med", "p(50)")
    mn = _mval(summary, "http_req_duration", "min")
    mx = _mval(summary, "http_req_duration", "max")

    thresholds: dict[str, Any] = {}
    for name, metric in (summary.get("metrics") or {}).items():
        th = metric.get("thresholds")
        if isinstance(th, dict):
            for expr, result in th.items():
                if isinstance(result, dict):
                    thresholds[f"{name}:{expr}"] = not result.get("ok", True) is False
                else:
                    thresholds[f"{name}:{expr}"] = bool(result)

    return {
        "engine": "k6",
        "ok": True,
        "degraded": False,
        "reason": None,
        "samples": int(count),
        "errors": int(errors),
        "error_rate": round(failed_rate, 5),
        "p95_ms": round(p95, 2),
        "p99_ms": round(p99, 2),
        "med_ms": round(med, 2),
        "min_ms": round(mn, 2),
        "max_ms": round(mx, 2),
        "avg_ms": round(avg, 2),
        "rps": round(rps, 2),
        "duration_s": round(duration, 1),
        "checks_passed": int(_mval(summary, "checks", "passes")),
        "checks_failed": int(_mval(summary, "checks", "fails")),
        "thresholds": thresholds,
        "histogram": [],
        "latencies": [],
    }


def run_k6(
    base: str,
    endpoints: list[dict[str, Any]],
    vus: int,
    duration_s: float,
    p95_threshold: int,
    error_threshold: float,
    log: Logger,
    artifact_dir: Path | None = None,
) -> dict[str, Any]:
    duration_str = f"{max(1, int(round(duration_s)))}s"
    script = build_script(endpoints, vus, duration_str, p95_threshold, error_threshold)
    workdir = Path(tempfile.mkdtemp(prefix="cg_k6_"))
    script_path = workdir / "load.js"
    summary_path = workdir / "summary.json"
    script_path.write_text(script, encoding="utf-8")

    cmd = [
        K6_BIN, "run",
        "--quiet",
        "--no-color",
        "--summary-export", str(summary_path),
        "--env", f"TARGET={base}",
        str(script_path),
    ]
    log(f"$ k6 run --vus {vus} --duration {duration_str} (target {base})")
    started = time.perf_counter()
    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=int(duration_s) + 120
        )
    except subprocess.TimeoutExpired:
        return _empty_result("k6", "k6 exceeded its time budget")
    except FileNotFoundError:
        return _empty_result("k6", "k6 binary disappeared mid-run")
    elapsed = time.perf_counter() - started

    for line in ((proc.stdout or "") + (proc.stderr or "")).splitlines()[-40:]:
        if line.strip():
            log(line.rstrip())

    if not summary_path.is_file():
        return _empty_result("k6", f"k6 produced no summary (exit {proc.returncode})")

    try:
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return _empty_result("k6", f"unreadable k6 summary: {exc}")

    result = parse_k6_summary(summary, elapsed)
    result["exit_code"] = proc.returncode
    # k6 exits 99 when a threshold fails — that is a real gate signal.
    result["thresholds_breached"] = proc.returncode != 0
    result["script"] = script

    if artifact_dir:
        try:
            artifact_dir.mkdir(parents=True, exist_ok=True)
            (artifact_dir / "k6-script.js").write_text(script, encoding="utf-8")
            (artifact_dir / "k6-summary.json").write_text(
                json.dumps(summary, indent=2), encoding="utf-8"
            )
            result["artifacts"] = ["k6-script.js", "k6-summary.json"]
        except OSError:
            pass
    return result


def run_load(
    base: str,
    endpoints: list[dict[str, Any]],
    vus: int,
    duration_s: float,
    p95_threshold: int,
    error_threshold: float,
    log: Logger,
    artifact_dir: Path | None = None,
    prefer: str = "auto",
) -> dict[str, Any]:
    """Pick the best available engine and run the load profile."""
    k6 = tool_get("k6")
    if prefer in {"auto", "k6"} and k6.get("available"):
        log(f"Load engine: k6 ({k6.get('version')})")
        result = run_k6(
            base, endpoints, vus, duration_s, p95_threshold, error_threshold, log, artifact_dir
        )
        if result.get("ok"):
            return result
        log(f"k6 run failed ({result.get('reason')}) — falling back to the built-in generator")
    elif prefer != "builtin":
        log(f"Load engine: built-in ({k6.get('detail')})")

    result = run_builtin(base, endpoints, vus, duration_s, log)
    if artifact_dir and result.get("ok"):
        try:
            artifact_dir.mkdir(parents=True, exist_ok=True)
            payload = {k: v for k, v in result.items() if k != "latencies"}
            (artifact_dir / "load-summary.json").write_text(
                json.dumps(payload, indent=2), encoding="utf-8"
            )
        except OSError:
            pass
    return result
